name = "idiom-learning-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "idiom-learning-db"
database_id = "099e488b-0bc5-4443-b07e-8adb0c6699dd"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Routes (optional)
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ] 